apiVersion: v1
kind: Service
metadata:
  name: incidentwatch-service
  labels:
    app: incidentwatch
spec:
  selector:
    app: incidentwatch
  ports:
    - name: http
      port: 8000        # puerto interno del servicio dentro del cluster
      targetPort: 8000  # puerto donde escucha el contenedor (Uvicorn)
  type: NodePort
